name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  CI:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '19.2.0'
        cache: 'yarn'

    - name: Install Dependencies
      run: yarn install --frozen-lockfile

    - name: Run Tests
      run: yarn  test:e2e
    
    - name: Build Application
      run: yarn build
  build-image:
    needs: CI
    runs-on: self-hosted
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Git Semantic Version
      uses: paulhatch/semantic-version@v5.4.0  
      with:
        tag_prefix: "v"
        major_pattern: "major:"
        minor_pattern: "feat:"
        version_format: "${major}.${minor}.${patch}-prerelease${increment}"  
        bump_each_commit: true
      id: version

    - name: Set Keys
      run: | 
        echo "NEW_VERSION=${{ steps.version.outputs.version }}" >> $GITHUB_ENV
        echo "DOCKER_CONTAINER=${{ vars.DOCKER_CONTAINER }}" >> $GITHUB_ENV

    - name: Docker Login 
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USER }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD

    - name: Build Image
      run: |
        docker build -t "$DOCKER_CONTAINER:$NEW_VERSION" .
        docker build -t "$DOCKER_CONTAINER:latest" .
        
    - name: Push Image
      run: |
        docker push "$DOCKER_CONTAINER:$NEW_VERSION"
        docker push "$DOCKER_CONTAINER:latest"
  
  deploy-image:
    needs: build-image
    runs-on: self-hosted
    steps:
    - name: Docker Login 
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USER }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD

    - name: Deploy
      env:
        DOCKER_CONTAINER: ${{ vars.DOCKER_CONTAINER }}
        NEW_VERSION: ${{ needs.build-image.outputs.version }}
      run: |
        docker compose pull
        docker compose up -d --remove-orphans

    - name: Docker Logout
      run: docker logout 
